import type { BoardData, CardKind, Confidence, ClarityCard, Connection, Topic } from './types'

export const kindMeta: Record<CardKind, { label: string; symbol: string; color: string }> = {
  question: { label: 'Question', symbol: '?', color: '#f2a64a' },
  knowledge: { label: 'Knowledge', symbol: '◆', color: '#557b72' },
  meaning: { label: 'Meaning', symbol: '✦', color: '#8e68aa' },
}

export const confidenceLabels: Record<Confidence, string> = {
  'first-hand': 'Cherry said or wrote this directly',
  'shared-with-me': 'Observed, recounted, or reported by Enzo',
  hypothesis: 'Tentative interpretation to test with Cherry',
}

const now = Date.now()

const card = (
  id: string,
  title: string,
  body: string,
  kind: CardKind,
  confidence: Confidence,
  topicId: string,
  x: number,
  y: number,
  source: string,
  status: ClarityCard['status'] = 'open',
): ClarityCard => ({
  id,
  title,
  body,
  kind,
  confidence,
  topicId,
  x,
  y,
  source,
  status,
  vx: 0,
  vy: 0,
  updatedAt: now,
})

export const topics: Topic[] = [
  { id: 'all', name: 'All threads', color: '#2c3834' },
  { id: 'story', name: 'The story so far', color: '#dd765c' },
  { id: 'nyc', name: 'NYC chapter & return', color: '#4d78a4' },
  { id: 'direction', name: 'Design, psychology & transfer', color: '#557b72' },
  { id: 'energy', name: 'Habits, energy & wellbeing', color: '#d49b3b' },
  { id: 'relationship', name: 'Relationship, trust & listening', color: '#b76f86' },
  { id: 'strengths', name: 'Strengths & capabilities', color: '#60865c' },
  { id: 'questions', name: 'Open questions for Cherry', color: '#8e68aa' },
]

export const starterCards: ClarityCard[] = [
  // ==================== STORY SO FAR ====================
  card(
    'cs-start',
    'Computer science as the starting path',
    'Cherry started out studying computer science. She excelled academically in difficult STEM courses—including calculus and differential equations—but recognized that she did not have an authentic personal reason for pursuing CS as a career. It gave proof of competence, but not daily fulfillment.',
    'knowledge',
    'shared-with-me',
    'story',
    -1020,
    -320,
    'Enzo’s account · Background',
  ),
  card(
    'turning-talk',
    'The conversation about setting up a life',
    'Enzo and Cherry had a deep, pivotal conversation about the danger of building a whole future around a discipline she already knew she did not enjoy (“if you’re studying something you know you don’t like, you’re setting your life up for failure”). Cherry listened, agreed with the risk, and made the conscious choice to step away from CS to explore fashion design.',
    'knowledge',
    'shared-with-me',
    'story',
    -700,
    -380,
    'Enzo & Cherry · Turning point',
  ),
  card(
    'fashion-choice',
    'Choosing fashion design with conviction',
    'After reflecting on what she loved, Cherry moved toward fashion design. She remains verbally set on design, even while experiencing uncertainty about daily execution, portfolio building, and school transfer options.',
    'knowledge',
    'shared-with-me',
    'story',
    -380,
    -320,
    'Enzo’s account · Fall 2026',
  ),
  card(
    'cafe-work',
    'Years of café work & practical independence',
    'Cherry built a sustained work history across Mr. Sun Tea (Cupertino), R&B Tea (San Jose), Chicha San Chen (Cupertino), and Cere-Tea (Saratoga) as a bobarista and shift lead. It demanded customer interaction, practical routine, and physical reliability while balancing full-time studies.',
    'knowledge',
    'shared-with-me',
    'story',
    -1020,
    -100,
    'Work record · 2022–2026',
  ),
  card(
    'quiet-compatibility',
    'Quiet companionship & mental harmony',
    'Enzo describes Cherry as analytical, quiet, and deeply mentally compatible. They can spend hours together in comfortable silence without feeling pressured to fill every gap with chatter. He values her silence specifically, viewing their bond as both romance and best friendship.',
    'knowledge',
    'shared-with-me',
    'story',
    -700,
    -100,
    'Enzo’s account · Relationship dynamic',
  ),
  card(
    'bold-style',
    'Confident style & solo independence',
    'Cherry moves through the world with natural independence: she attends concerts and restaurants alone, and has a distinctive, sharp aesthetic (white dresses with tall boots and fishnets, dark edgier looks, piercings). Her independence is an active practice, not a lack of emotional needs.',
    'knowledge',
    'shared-with-me',
    'story',
    -380,
    -100,
    'Observations & photos',
  ),

  // ==================== NYC CHAPTER & RETURN ====================
  card(
    'cere-tea-departure',
    'Leaving Cere-Tea for New York City',
    'In summer 2026, Cherry made a bold geographic move: she left her familiar café role at Cere-Tea in Saratoga and moved across the country to Manhattan to work as a sales assistant at Honggang Textile in Midtown.',
    'knowledge',
    'shared-with-me',
    'nyc',
    -1020,
    220,
    'Summer 2026 milestone',
  ),
  card(
    'nyc-textile-role',
    'Honggang Textile: Gaining industry footing',
    'In Midtown Manhattan, Cherry organized fabric hanger cards, curated textile selections, managed spreadsheets, supported client meetings, and met representatives from eight fashion brands. It was a concrete attempt to gain practical industry footing in New York.',
    'knowledge',
    'shared-with-me',
    'nyc',
    -680,
    220,
    'Employment details · July–August 2026',
  ),
  card(
    'textile-dismissal',
    'The sudden end of the textile position',
    'Cherry came to believe the employer was trying to take advantage of her, and the role ended in dismissal. The loss disrupted her living and working plans in NYC and brought sharp embarrassment and distress.',
    'knowledge',
    'shared-with-me',
    'nyc',
    -340,
    220,
    'Sensitive · Enzo’s account',
  ),
  card(
    'stay-fit-ambition',
    'Considering staying in NYC for FIT',
    'After the job ended, Cherry considered remaining in New York for a full year to apply to the Fashion Institute of Technology (FIT), working interim jobs (including about a week stocking at a Japanese store). The plan held both authentic creative aspiration and a reluctance to return home after being fired.',
    'knowledge',
    'shared-with-me',
    'nyc',
    0,
    220,
    'Enzo’s account · NYC chapter',
  ),
  card(
    'shame-call',
    'The late-night phone call about shame',
    'In an emotional phone conversation, Enzo asked Cherry whether she was staying in NYC partly to avoid facing her parents after losing the job. Cherry acknowledged that shame was a central reason. She cried on the call, slept on it, and decided to return home to the Bay Area.',
    'knowledge',
    'first-hand',
    'nyc',
    -340,
    440,
    'Cherry & Enzo · Late night call',
  ),
  card(
    'return-home',
    'Returning to San Jose & reclaiming options',
    'Returning to the Bay Area was not a defeat; it was a decision to step out of an unsustainable situation in NYC and reassess her path with family proximity, lower financial panic, and time to breathe.',
    'meaning',
    'hypothesis',
    'nyc',
    0,
    440,
    'Interpretation · To explore with Cherry',
  ),

  // ==================== DESIGN, PSYCHOLOGY & TRANSFER ====================
  card(
    'community-college-present',
    'Attending De Anza & West Valley College',
    'Cherry is currently living in San Jose and taking coursework across De Anza College and West Valley College (approximately her third year in CC), navigating both general education requirements and West Valley’s Cilker School of Art and Design.',
    'knowledge',
    'shared-with-me',
    'direction',
    220,
    220,
    'Current enrollment · Fall 2026',
  ),
  card(
    'transfer-routes',
    'Evaluating transfer paths: FIT, ArtCenter, Pratt',
    'Her current transfer research spans top design institutions: Fashion Institute of Technology (FIT) in NYC, ArtCenter College of Design (ACCD) in Pasadena, and Pratt Institute. Each has distinct portfolio requirements, unit articulations, and program cultures that need objective comparison.',
    'knowledge',
    'shared-with-me',
    'direction',
    580,
    220,
    'Transfer exploration',
  ),
  card(
    'psychology-curiosity',
    'Psychology as an authentic parallel interest',
    'Cherry has long been interested in psychology—previously considering it as a minor, and now exploring it alongside design. Understanding cognition, behavior, and human emotion may be an authentic intellectual spark rather than just a distraction from design.',
    'knowledge',
    'shared-with-me',
    'direction',
    940,
    220,
    'Cherry’s expressed interest',
  ),
  card(
    'portfolio-friction',
    'The friction of self-directed portfolio work',
    'Enzo created a portfolio website for Cherry, but progress has moved slowly. Unlike graded STEM assignments with unambiguous answers and deadlines, independent design requires picking a concept from scratch, tolerating imperfect early drafts, and exposing subjective taste to judgment.',
    'knowledge',
    'shared-with-me',
    'direction',
    220,
    440,
    'Creative process observation',
  ),
  card(
    'sketching-practice',
    'Sustaining regular sketching & drawing practice',
    'Cherry has expressed that her sketching skill does not yet match her aesthetic eye, which can make drawing feel discouraging. Finding low-stakes, playful ways to sketch without pressure is a key hurdle.',
    'knowledge',
    'shared-with-me',
    'direction',
    580,
    440,
    'Design skill observation',
  ),
  card(
    'creative-spark-test',
    'What is the smallest honest creative experiment?',
    'Instead of feeling overwhelmed by a full multi-page admissions portfolio: what is one single miniature project (styling three outfits, making a moodboard, altering a garment, or doing five 10-minute sketches) that would reveal whether the daily work feels energizing?',
    'question',
    'hypothesis',
    'direction',
    940,
    440,
    'Question for Cherry',
  ),

  // ==================== HABITS, ENERGY & WELLBEING ====================
  card(
    'august-message',
    '“This is terrible, this is not like how I was” (Aug 8, 2026)',
    'Direct messages from Cherry at 9:28 PM:\n“My room’s a mess, I dont care about work, I only brush my teeth in the morning because I have to be in close proximity to my coworker and sometimes customers (but I rly struggle to floss), im so unmotivated, I havent even been learning mandarin, I need to learn something, but every night, I just dont. I go to work, I spend money, and then it’s 11 pm. I feel lonely whenever Im home. I need to feel a purpose to do something, but I just feel apathetic. I try to start a task, but then i give up and go to sleep. This is terrible, this is not like how I was.”',
    'knowledge',
    'first-hand',
    'energy',
    1180,
    -180,
    'Cherry · Quoted message (Aug 8, 2026)',
  ),
  card(
    'apathy-vs-purpose',
    'The essential search for a felt purpose',
    'Cherry explicitly linked action to purpose: she needs to feel a reason to do something, but when disconnected from that reason, she experiences apathy. This is not laziness—it is the natural friction of spending heavy cognitive energy without an internal compass.',
    'meaning',
    'hypothesis',
    'energy',
    1520,
    -180,
    'Cherry’s self-reflection · August 2026',
  ),
  card(
    'routine-friction',
    'Daily routines as an index of internal state',
    'Struggling with basic routines (room clutter, evening exhaustion, task initiation) was distressing to Cherry specifically because it felt unlike her past self. Recognizing that energy fluctuates with stress and isolation can remove self-blame.',
    'meaning',
    'hypothesis',
    'energy',
    1860,
    -180,
    'Observation & reflection',
  ),
  card(
    'high-performance-loop',
    'Hypothesis: The high-performance safety loop',
    'When open-ended creative identity and future direction feel ambiguous, taking a heavy load of difficult classes provides familiar structure, clear syllabi, and objective proof of intelligence. It creates a feeling of competence, even while deferring the less structured creative work.',
    'meaning',
    'hypothesis',
    'energy',
    1180,
    60,
    'Enzo’s central hypothesis · To test',
  ),
  card(
    'safety-in-structure',
    'Differentiating capacity from available energy',
    'Cherry has proven immense intellectual stamina. The gap she experiences is not one of ability, but of emotional safety, restorative rest, and authentic personal resonance with what she is building.',
    'meaning',
    'hypothesis',
    'energy',
    1520,
    60,
    'Compassionate framing',
  ),
  card(
    'q-how-i-was',
    'What did “how I was” mean to you in August?',
    'When you wrote “this is not like how I was,” which specific earlier qualities did you miss most? Was it high energy, academic intensity, curiosity, routine, or feeling close to people? Which of those matter most to you today?',
    'question',
    'hypothesis',
    'energy',
    1860,
    60,
    'Open Question for Cherry',
  ),

  // ==================== RELATIONSHIP, TRUST & LISTENING ====================
  card(
    'first-date-concert',
    'The concert origin story (July 2025)',
    'Cherry was planning to attend a concert alone. When Enzo asked who she was going with and she said “Oh I’m going alone,” Enzo replied “nah” and came along. What started as an unpretentious, spontaneous evening became their first date and the foundation of their relationship.',
    'knowledge',
    'shared-with-me',
    'relationship',
    -80,
    -580,
    'Relationship origin · July 21, 2025',
  ),
  card(
    'one-year-anniversary',
    'First anniversary site & deep commitment',
    'On July 21, 2026, while Cherry was living in NYC, Enzo built an anniversary website preserving their memories, photographs, and shared laughs: “I love your mind, I love your soul, your laugh, your confidence, your silence, your precision and your determination… Happy one-year, otw to a hundred more.”',
    'knowledge',
    'shared-with-me',
    'relationship',
    260,
    -580,
    'Anniversary letter · July 2026',
  ),
  card(
    'berkeley-distance-fear',
    'Vulnerable fear of “someone better” at Berkeley',
    'With Enzo now attending UC Berkeley while Cherry remains at community college sorting out her transfer, Cherry voiced a vulnerable insecurity that Enzo might meet someone “better” at Berkeley. Affection and commitment are not trophies awarded for academic speed.',
    'knowledge',
    'first-hand',
    'relationship',
    600,
    -580,
    'Cherry to Enzo · Vulnerable disclosure',
  ),
  card(
    'small-things-promise',
    '“A lot of small useless things” (Sept 23, 2026)',
    'After ending sessions with a new therapist on September 23, 2026, Cherry hesitated to share her worries with Enzo, explaining that what bothers her can feel like “a lot of small useless things” that he might brush off as irrelevant. Enzo made a clear commitment to listen without dismissing.',
    'knowledge',
    'first-hand',
    'relationship',
    -80,
    -380,
    'Cherry & Enzo · Conversation Sept 23, 2026',
  ),
  card(
    'listening-vs-fixing',
    'Hypothesis: Room to be heard without an action plan',
    'Enzo naturally defaults to systems, diagnosing root causes, and creating action plans. But being heard often doesn’t require a 5-step fix; it requires presence, reassurance, and validation that everyday feelings matter even if they don’t produce a neat solution.',
    'meaning',
    'hypothesis',
    'relationship',
    260,
    -380,
    'Relationship communication hypothesis',
  ),
  card(
    'security-boundary',
    'Building security across divergent school stages',
    'Cherry drives up to visit Enzo at Berkeley roughly once every two weeks. Navigating different campuses and schedules requires shared warmth, honest boundaries, and ensuring neither partner’s self-worth is tied to the other’s academic status.',
    'meaning',
    'hypothesis',
    'relationship',
    600,
    -380,
    'Relationship growth',
  ),

  // ==================== STRENGTHS & CAPABILITIES ====================
  card(
    'stem-mastery',
    'Exceptional academic proficiency in STEM',
    'Cherry graduated from Cupertino High School with a 3.93 GPA, earned Dean’s List honors at De Anza, and consistently aces demanding courses in computer science, linear algebra, differential equations, and chemistry. Her intellect and learning capacity are exceptionally strong.',
    'knowledge',
    'shared-with-me',
    'strengths',
    940,
    -580,
    'Academic record & transcript history',
  ),
  card(
    'practical-resilience',
    'Real-world customer resilience & independence',
    'Years of multi-shift café work and taking the leap to move solo to New York demonstrate practical grit, social competence under pressure, and a willingness to step outside familiar comfort zones.',
    'knowledge',
    'shared-with-me',
    'strengths',
    1280,
    -580,
    'Observed strengths',
  ),
  card(
    'intellectual-depth',
    'Intellectual honesty & refusal of easy answers',
    'Cherry is direct, honest, and resists telling people what they want to hear. When a path doesn’t feel authentic (like CS or an unfulfilling job), she is willing to confront that reality rather than coast on comfortable illusions.',
    'knowledge',
    'shared-with-me',
    'strengths',
    1620,
    -580,
    'Personal character',
  ),
  card(
    'capacity-vs-energy',
    'Ability is not the constraint',
    'The pattern across school, work, and creative projects confirms that Cherry does not suffer from any lack of cognitive ability. The core work is aligning her formidable capacity with genuine interest, emotional safety, and sustainable daily energy.',
    'meaning',
    'hypothesis',
    'strengths',
    1100,
    -380,
    'Core insight',
  ),

  // ==================== OPEN QUESTIONS FOR CHERRY ====================
  card(
    'q-success-definition',
    'What does a good life look like beyond grades?',
    'If no one could see your grades, school name, income, or résumé, what would you still be curious enough to learn? What would an ordinary Tuesday that feels joyful and peaceful look like for you a year from now?',
    'question',
    'hypothesis',
    'questions',
    100,
    780,
    'Open Question for Cherry',
  ),
  card(
    'q-creative-energy',
    'What parts of fashion feel genuinely absorbing?',
    'Do you most enjoy styling silhouettes, feeling and sourcing fabrics, patternmaking, fashion history, illustration, or understanding how brands operate? If no application or critique were involved, what would you voluntarily make this week?',
    'question',
    'hypothesis',
    'questions',
    460,
    780,
    'Open Question for Cherry',
  ),
  card(
    'q-timeline-pace',
    'Whose timeline is “behind”?',
    'When you feel behind, whose clock are you measuring against? What would a pace of life and education that feels chosen and self-authored look like, rather than one defined by comparison?',
    'question',
    'hypothesis',
    'questions',
    820,
    780,
    'Open Question for Cherry',
  ),
  card(
    'q-what-support-feels-like',
    'What does supportive listening feel like for you?',
    'When you share something that feels like “small useless things,” what response actually feels good? Silence? A hug? Humor? Questions? Helping make a plan only when asked? You get to define what you want.',
    'question',
    'hypothesis',
    'questions',
    1180,
    780,
    'Open Question for Cherry',
  ),
  card(
    'cherry-final-editor',
    'Cherry is the author & final editor of this map',
    'Clarity is a draft workspace, not a clinical dossier. Cherry has sovereign ownership: she can revise descriptions, make cards private, delete what doesn’t belong, and reject any outside interpretation. Her perspective is the primary truth of this map.',
    'meaning',
    'first-hand',
    'questions',
    1520,
    780,
    'Guiding Principle · Clarity',
    'resolved',
  ),
]

export const starterConnections: Array<[string, string]> = [
  // Story -> Turning point -> Fashion
  ['cs-start', 'turning-talk'],
  ['turning-talk', 'fashion-choice'],
  ['cs-start', 'stem-mastery'],
  ['turning-talk', 'intellectual-depth'],

  // Story & Café work -> NYC leap
  ['cafe-work', 'cere-tea-departure'],
  ['cere-tea-departure', 'nyc-textile-role'],
  ['nyc-textile-role', 'textile-dismissal'],
  ['textile-dismissal', 'stay-fit-ambition'],
  ['stay-fit-ambition', 'shame-call'],
  ['shame-call', 'return-home'],

  // Return -> Community College & Direction
  ['return-home', 'community-college-present'],
  ['fashion-choice', 'community-college-present'],
  ['community-college-present', 'transfer-routes'],
  ['community-college-present', 'portfolio-friction'],
  ['portfolio-friction', 'sketching-practice'],
  ['sketching-practice', 'creative-spark-test'],
  ['community-college-present', 'psychology-curiosity'],

  // NYC experience -> Energy & Wellbeing
  ['textile-dismissal', 'august-message'],
  ['august-message', 'apathy-vs-purpose'],
  ['august-message', 'routine-friction'],
  ['august-message', 'q-how-i-was'],
  ['apathy-vs-purpose', 'creative-spark-test'],

  // High performance loop
  ['stem-mastery', 'high-performance-loop'],
  ['community-college-present', 'high-performance-loop'],
  ['high-performance-loop', 'safety-in-structure'],
  ['safety-in-structure', 'capacity-vs-energy'],

  // Relationship threads
  ['first-date-concert', 'bold-style'],
  ['first-date-concert', 'quiet-compatibility'],
  ['quiet-compatibility', 'one-year-anniversary'],
  ['one-year-anniversary', 'berkeley-distance-fear'],
  ['berkeley-distance-fear', 'security-boundary'],
  ['small-things-promise', 'listening-vs-fixing'],
  ['listening-vs-fixing', 'q-what-support-feels-like'],
  ['berkeley-distance-fear', 'q-timeline-pace'],

  // Questions & Authorship
  ['capacity-vs-energy', 'q-success-definition'],
  ['fashion-choice', 'q-creative-energy'],
  ['community-college-present', 'q-timeline-pace'],
  ['listening-vs-fixing', 'cherry-final-editor'],
  ['shame-call', 'q-timeline-pace'],
]

export const starterData: BoardData = {
  contentVersion: 3,
  topics,
  cards: starterCards,
  connections: starterConnections.map(([from, to], index): Connection => ({
    id: `link-${index + 1}`,
    from,
    to,
  })),
}
